name: Pastel
options:
  bundleIdPrefix: app.pastel
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.4.0"
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-Modern
    from: "1.1.0"
targets:
  Pastel:
    type: application
    platform: macOS
    sources:
      - Pastel
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.pastel.Pastel
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: Pastel/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Pastel/Resources/Pastel.entitlements
        GENERATE_INFOPLIST_FILE: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_IDENTITY: "-"
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    dependencies:
      - package: KeyboardShortcuts
      - package: LaunchAtLogin
